* общее описание игры
  Две или более противоборствующие комманды. Каждая комманда состоит из
  + кондитер
    производит пастилу и карамель. Строит из пастилы, намазывая на края карамель, укрепления. То есть
    не только всякие там заборы, а любые строения, дома. Излишки, производимых им карамели или пастилы
    могут использовать другие персонажи. Основное орудие - большая пастила, примерно в полтора раза больше
    самого кондитера. Он ей бьёт по башке и по туловищу с боку.

  + ребёнок
    мастерит карамельки и маленькие конфетки из пастилы, которые получает от кондитера, карамельщика или 
    повелителя бочки. Конфетами или кидается или ест их, восполняя потери.

  + карамельщик
    Приготавливает карамель на ходу или берёт её от кондитера и повелителя бочки. Накопленную карамель 
    изливает на врагов подобно пожарнику. Может регулировать напор. 
  
  + повелитель бочки
    Высасывает из врагов карамель, а также поглощает любые остатки карамели вокруг себя, включая потерявших
    пластичность персонажей. Бочка с карамелью распределяется по находящимся рядом дружественным персонажам.
    Бочка всегда немного пополняется, карамель как бы высасывается из пространства.
    
  Все персонажи имеют запас карамели и он одновременно является ресурсом для действий(стрелять, лепить и тд),
  так и жизненными силами. Чем меньше карамели, тем меньше пластичность персонажа(становится медленнее). 
  Персонаж без просто замирает и либо его собирает карамельщик или повелитель бочки, либо дружественный 
  повелитель бочки может подпитать его карамелью. Собранный персонаж через какое-то время выпрыгивает из
  бочки дружественного повелителя бочки.
  Если повелитель бочки твердеет, то постепенно из-за увеличивающейся карамели в бочке, он всё равно 
  восстанавливает пластичность.
